branch-defaults:
  main:
    environment: jalon2-env
    group_suffix: null
environment-defaults:
  jalon2-env:
    branch: null
    repository: null
global:
  application_name: jalon2-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
